'use strict';

module.exports = {
  DEFERRABLE_INITIALLY_DEFERRED: 'DEFERRABLE INITIALLY DEFERRED',
  DEFERRABLE_INITIALLY_IMMEDIATE: 'DEFERRABLE INITIALLY IMMEDIATE',
  NOT_DEFERRABLE: 'NOT DEFERRABLE',
  ALL_DEFERRED: 'SET CONSTRAINTS ALL DEFERRED'
};
